[tool.poetry]
name = "product-org-reco-engine"
version = "0.1.0"
description = "Local development environment for Product Organisation Recommendation Engine"
authors = ["Rohit Kamble", "Manas Chandan Behera"]

[tool.poetry.dependencies]
python = "^3.11"

# Frontend
streamlit = "^1.37"
plotly = "^5.24"

# Backend
fastapi = "^0.115"
uvicorn = "^0.30"

# Data & Batch
pandas = "^2.2"
pyspark = "^3.5"
mlxtend = "^0.23"
networkx = "^3.3"
ortools = "^9.10"

# Databases
sqlalchemy = "^2.0"
psycopg2-binary = "^2.9"
neo4j = "^5.20"

# Utils
pydantic = "^2.9"
requests = "^2.32"
loguru = "^0.7"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
black = "^24.4"
isort = "^5.13"
mypy = "^1.11"
pre-commit = "^3.8"
